name: drupal-starter-project
recipe: drupal9

config:
  php: "8.1"
  webroot: web
  composer_version: "2.3.3"

services:
  appserver:
    run:
      - composer install --no-interaction

  node:
    type: node:16
    run:
      - yarn install
      - gulp build

  # Uncomment to use ansible to store encrypted secrets.
  # ansible:
  #   type: python
  #   via: cli
  #   build_as_root:
  #     - pip install ansible
  #   run:
  #     - bin/setup-ansible
  #     - ansible-playbook ansible/setup-lando.yml --vault-id=ansible/.vault-id

tooling:
  ansible-playbook:
    service: ansible
  ansible-vault:
    service: ansible
  gulp:
    service: node
  yarn:
    service: node
  phpcs:
    service: appserver
    cmd: vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
